## Assignment 

1- create an array of shape (10, 10) with uint8 random values.

2- print the shape, size and dimension.

3- compute the sum of the third to last row.

4- compute the average of the columns

In [17]:
import numpy as np

def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("size = ", a.size)
    print()


ar_05 = np.random.randint(1,20, (10,10), dtype = 'uint8')
array_properties(ar_05)

print(("last row: "), ar_05[-1])
print()
print(("2nd last row: "), ar_05[-2])
print()
print(("3rd last row: "), ar_05[-3])

total = ar_05[-1] + ar_05[-2] + ar_05[-3]  
print()
print(("Sum of three last row: "),total)

total_all = np.sum(ar_05,axis=0)  

average = total_all / 10
print()
print(("Average of column: "),average)

a = 
 [[ 2 18 11 13 10 19  3  6  3  2]
 [13 18  8 13 15 17 17  1 12 17]
 [ 2 18 16 18  1 14 14  8 11  8]
 [10 16  7 17  7  8 16  3 12 18]
 [ 1 12  9 14 13  8  5  7  5 15]
 [ 3 14  1  6 15 10  5  3  1  8]
 [16 10 10 12 16  6  7 16  3  2]
 [ 5  9  8  5  7 16  1 11 11 15]
 [15 10  1 19 18  4  7 18 12  5]
 [16  1 13  1  1 11 16 13  4 13]]
dim =  2
shape =  (10, 10)
size =  100

last row:  [16  1 13  1  1 11 16 13  4 13]

2nd last row:  [15 10  1 19 18  4  7 18 12  5]

3rd last row:  [ 5  9  8  5  7 16  1 11 11 15]

Sum of three last row:  [36 20 22 25 26 31 24 42 27 33]

Average of column:  [ 8.3 12.6  8.4 11.8 10.3 11.3  9.1  8.6  7.4 10.3]
