## ASSIGNMENT 9

1- Create a random array A, of shape (6x6) using randintand seed 2.

2- Convert the array A, to an identity matrix I.


In [5]:
def array_properties(a):
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()
    print("a = \n", a)

In [8]:
import numpy as np

np.random.seed(2)

A = np.random.randint(1, 40,(6,6))
array_properties(A)

M,N = A.shape

I = np.eye(N)

array_properties(I)

dim =  2
shape =  (6, 6)
datatype =  int32
size =  36

a = 
 [[16  9 23 19 12  8]
 [35 32 12 22 32 27]
 [21 38  4 39  5 39]
 [34  4  6 25  5  7]
 [32 20 32  3 17 13]
 [ 5 27 16  9 16  9]]
dim =  2
shape =  (6, 6)
datatype =  float64
size =  36

a = 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [9]:
A = np.identity(6)
array_properties(A)

dim =  2
shape =  (6, 6)
datatype =  float64
size =  36

a = 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
